### ISSUE TITLE
Use Xenon 1.2.0

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/pyxenon#11]
Currently pyxenon is using Xenon 1.1.0 jar. [Xenon](https://github.com/NLeSC/Xenon) version 1.2.0 was just released. pyxenon should use the latest Xenon version.

**Comment by jmaassen** [comment]
I've released 1.2.1, which fixed the jobs.waitUntil* bug. Please use that one instead of 1.2.0

**Comment by jhidding** [comment]
Is this still relevant?

**Comment by sverhoeven** [comment]
No, it isn't anymore as pyxenon is based on Xenon 2 snapshot.
