### ISSUE TITLE
Fine-grained exception support

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/pyxenon#12]
From xenon/exceptions.py, it seems that only catching xenon.XenonException is supported, via its Python representation as xenon.exceptions.XenonException. I want to make a directory, and ignore a xenon.files.PathAlreadyExistsException if it occurs, but not any other potential error conditions. Having that path already exist is fine for my application, but if it doesn't exist and there's a problem creating it, then I want the exception to propagate. So I want to catch only xenon.files.PathAlreadyExistsException, but it looks like I can't do that.

If it can be done, then consider this a request for more documentation :).

**Comment by LourensVeen** [comment]
With thanks to @fdiblen for the pointer, it seems like it can be done, using

`import jpype`
and then
`except jpype.JException(xenon.nl.esciencecenter.xenon.files.PathAlreadyExistsException):`

Would be nice if this could be added to the docs. And perhaps it makes more sense to do xenon.XenonException via this mechanism as well, for consistency?

**Comment by jhidding** [comment]
Since all of pyxenon is replaced, I'll close this issue for now.

**Comment by LourensVeen** [comment]
Agreed. As long as the new pyxenon supports this, of course :).
