### ISSUE TITLE
Exceptions are missing?

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/pyxenon#20]
I'm doing `filesystem.create_directories(path)` on a path that already exists. I'd expect that to raise a `xenon.PathAlreadyExistsException`, which I'd like to catch and ignore. Instead, I'm getting

```E           grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.ALREADY_EXISTS, file adaptor: Path already exists: /tmp/pytest-of-lourens/pytest-238/test_stage_api0)>```

In fact, I'm not seeing anything exception-related in pyxenon 2.

**Comment by LourensVeen** [comment]
Temporary workaround:
```
        except grpc._channel._Rendezvous as e:
            if e.code() == 'StatusCode.ALREADY_EXISTS':
                pass
```

**Comment by jhidding** [comment]
Yes. It may be more doable to create a generic XenonException class, since the rendezvous messages do not map 1-1 to the Xenon API

**Comment by LourensVeen** [comment]
Ah, but see https://github.com/NLeSC/pyxenon/issues/12

The point of exceptions is that they're an error handling mechanism. If there's only one class, then error handling quickly becomes limited to "Hello user, there was some kind of error, sorry.". You need those fine-grained exceptions to actually handle the error situation, or at least to give a useful error message.

**Comment by jhidding** [comment]
You are correct.

**Comment by jhidding** [comment]
btw: the grpc exception class is ``grpc.RpcError``

**Comment by jhidding** [comment]
@LourensVeen the desired functionality is now in develop branch. Currently only the  PathAlreadyExistsException has its own counterpart, since it takes a lot of copy/paste monkey coding to get all of them in order. Let me know if you have other exception classes that should have priority.

**Comment by LourensVeen** [comment]
That works for me, let's close this and I'll file pull requests for whatever else I need.

**Comment by LourensVeen** [comment]
Hold on, now I'm getting
```
xenon.exceptions.UnknownRpcException: Xenon: "file adaptor: Path already exists: /tmp/pytest-of-lourens/pytest-294/test_stage_api0" in create_directories
```
That's different, but it's still not a specific one.

**Comment by jhidding** [comment]
Aha! But that is a different function throwing it ;), I fixed it for ``create_directory``. Stefan and I are working on a more durable solution.
