### ISSUE TITLE
CopyMode missing

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/pyxenon#21]
I can't call Filesystem.copy(), because it seems that xenon.filesystems.CopyMode is missing. I think this is a known issue, because it's commented out in objects.py. If I comment it back in, I get a grpc error, so I guess something else needs to happen for that to work...

**Comment by jhidding** [comment]
In a previous version of xenon-grpc, CopyMode was a top-level enum. Now it is embedded in CopyRequest. So something like:

```python
from xenon import (FileSystem, CopyRequest, Path)

xenon.init()

with FileSystem.create(adaptor='file') as local_fs:
    remote_fs = FileSystem.create(adaptor='sftp', location='', certificate_credential=...)
    local_fs.copy(Path("local_file"), remote_fs, Path("remote_file"), mode=CopyRequest.CREATE, recursive=False)
```

I know it's not perfect.

**Comment by jhidding** [comment]
CopyMode and CopyRequest now both work.
