### ISSUE TITLE
Do we need a xenon.Job class?

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/pyxenon#24]
The Xenon 2 Java API has done away with job objects, instead using simple strings to identify jobs. While slightly less type-safe, this is much easier, since I can easy serialise strings.

PyXenon deviates from Xenon, in that it does have a Job class, with a single `id` attribute. Maybe it can follow the Java API and just use a string?

**Comment by LourensVeen** [comment]
Also, on deserialising, how do I create a Job object again? xenon.objects.Job(id_string) tells me it wants an additional `wrapped` argument.

**Comment by jhidding** [comment]
The wrapper objects are not meant to be constructed by the user. Converting Jobs to strings means strings have to be converted to Jobs in the case where a function needs a Job (see xenon.proto file). I consider it best not to touch the Job object and just leave them as black-box identifiers.
