### ISSUE TITLE
JobDescription does not accept Path for working_directory

### ISSUE THREAD

**Issue by LourensVeen** [NLeSC/pyxenon#26]
If I try to use a pyxenon Path object for the working_directory parameter to the xenon.JobDescription constructor, then I get an error message saying it wants either `bytes` or `unicode`. So I have to manually convert to a string, which is odd, since it really is a path that we want to set here.

**Comment by jhidding** [comment]
Yes. Easy fix, another class that needs a wrapper.

Op zo 3 dec. 2017 om 10:20 schreef Lourens Veen <notifications@github.com>:
