### ISSUE TITLE
Catchup to xenon-grpc v2.2.0

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/pyxenon#27]
Xeno grpc had 2 minor releases see https://github.com/NLeSC/xenon-grpc/blob/master/CHANGELOG.md.

These releases extended the api with new methods and fields.

Please expose the new v2.2.0 grpc api via pyxenon.

**Comment by jhidding** [comment]
I was doing just that, but nothing works! See: https://github.com/NLeSC/xenon-grpc/issues/37

**Comment by sverhoeven** [comment]
Please try again with xenon-grpc v2.2.1
